/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ForgotpasswordRouteImport } from './routes/forgotpassword'
import { Route as IndexRouteImport } from './routes/index'
import { Route as protectedProfileRouteImport } from './routes/(protected)/profile'
import { Route as protectedOnboardingRouteImport } from './routes/(protected)/onboarding'
import { Route as protectedFavoritesRouteImport } from './routes/(protected)/favorites'
import { Route as protectedEventsRouteImport } from './routes/(protected)/events'
import { Route as protectedEventCalendarRouteImport } from './routes/(protected)/event-calendar'
import { Route as protectedCreateEventRouteImport } from './routes/(protected)/create-event'
import { Route as protectedUserIdRouteImport } from './routes/(protected)/user/$id'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotpasswordRoute = ForgotpasswordRouteImport.update({
  id: '/forgotpassword',
  path: '/forgotpassword',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedProfileRoute = protectedProfileRouteImport.update({
  id: '/(protected)/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedOnboardingRoute = protectedOnboardingRouteImport.update({
  id: '/(protected)/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedFavoritesRoute = protectedFavoritesRouteImport.update({
  id: '/(protected)/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedEventsRoute = protectedEventsRouteImport.update({
  id: '/(protected)/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedEventCalendarRoute = protectedEventCalendarRouteImport.update({
  id: '/(protected)/event-calendar',
  path: '/event-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedCreateEventRoute = protectedCreateEventRouteImport.update({
  id: '/(protected)/create-event',
  path: '/create-event',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedUserIdRoute = protectedUserIdRouteImport.update({
  id: '/(protected)/user/$id',
  path: '/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgotpassword': typeof ForgotpasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/create-event': typeof protectedCreateEventRoute
  '/event-calendar': typeof protectedEventCalendarRoute
  '/events': typeof protectedEventsRoute
  '/favorites': typeof protectedFavoritesRoute
  '/onboarding': typeof protectedOnboardingRoute
  '/profile': typeof protectedProfileRoute
  '/user/$id': typeof protectedUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgotpassword': typeof ForgotpasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/create-event': typeof protectedCreateEventRoute
  '/event-calendar': typeof protectedEventCalendarRoute
  '/events': typeof protectedEventsRoute
  '/favorites': typeof protectedFavoritesRoute
  '/onboarding': typeof protectedOnboardingRoute
  '/profile': typeof protectedProfileRoute
  '/user/$id': typeof protectedUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgotpassword': typeof ForgotpasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/(protected)/create-event': typeof protectedCreateEventRoute
  '/(protected)/event-calendar': typeof protectedEventCalendarRoute
  '/(protected)/events': typeof protectedEventsRoute
  '/(protected)/favorites': typeof protectedFavoritesRoute
  '/(protected)/onboarding': typeof protectedOnboardingRoute
  '/(protected)/profile': typeof protectedProfileRoute
  '/(protected)/user/$id': typeof protectedUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgotpassword'
    | '/signin'
    | '/signup'
    | '/create-event'
    | '/event-calendar'
    | '/events'
    | '/favorites'
    | '/onboarding'
    | '/profile'
    | '/user/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgotpassword'
    | '/signin'
    | '/signup'
    | '/create-event'
    | '/event-calendar'
    | '/events'
    | '/favorites'
    | '/onboarding'
    | '/profile'
    | '/user/$id'
  id:
    | '__root__'
    | '/'
    | '/forgotpassword'
    | '/signin'
    | '/signup'
    | '/(protected)/create-event'
    | '/(protected)/event-calendar'
    | '/(protected)/events'
    | '/(protected)/favorites'
    | '/(protected)/onboarding'
    | '/(protected)/profile'
    | '/(protected)/user/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotpasswordRoute: typeof ForgotpasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  protectedCreateEventRoute: typeof protectedCreateEventRoute
  protectedEventCalendarRoute: typeof protectedEventCalendarRoute
  protectedEventsRoute: typeof protectedEventsRoute
  protectedFavoritesRoute: typeof protectedFavoritesRoute
  protectedOnboardingRoute: typeof protectedOnboardingRoute
  protectedProfileRoute: typeof protectedProfileRoute
  protectedUserIdRoute: typeof protectedUserIdRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$'
  id: '__root__' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgotpassword': {
      id: '/forgotpassword'
      path: '/forgotpassword'
      fullPath: '/forgotpassword'
      preLoaderRoute: typeof ForgotpasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/profile': {
      id: '/(protected)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof protectedProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/onboarding': {
      id: '/(protected)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof protectedOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/favorites': {
      id: '/(protected)/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof protectedFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/events': {
      id: '/(protected)/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof protectedEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/event-calendar': {
      id: '/(protected)/event-calendar'
      path: '/event-calendar'
      fullPath: '/event-calendar'
      preLoaderRoute: typeof protectedEventCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/create-event': {
      id: '/(protected)/create-event'
      path: '/create-event'
      fullPath: '/create-event'
      preLoaderRoute: typeof protectedCreateEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/user/$id': {
      id: '/(protected)/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof protectedUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotpasswordRoute: ForgotpasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  protectedCreateEventRoute: protectedCreateEventRoute,
  protectedEventCalendarRoute: protectedEventCalendarRoute,
  protectedEventsRoute: protectedEventsRoute,
  protectedFavoritesRoute: protectedFavoritesRoute,
  protectedOnboardingRoute: protectedOnboardingRoute,
  protectedProfileRoute: protectedProfileRoute,
  protectedUserIdRoute: protectedUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
